const MEASUREMENT_TABLE = {
  "-5": { mass_imp: "12 oz.", mass_met: "750 g", time: "1/8 second", dist_imp: "1 inch", dist_met: "6 cm", vol_imp: "1/32 cft.", vol_met: ".0008 m3", benchmark: "—" },
  "-4": { mass_imp: "1.5 lbs.", mass_met: "1.5 kg", time: "1/4 second", dist_imp: "3 inches", dist_met: "12 cm", vol_imp: "1/16 cft.", vol_met: ".0017 m3", benchmark: "A soccer ball or football" },
  "-3": { mass_imp: "3 lbs.", mass_met: "3 kg", time: "1/2 second", dist_imp: "6 inches", dist_met: "25 cm", vol_imp: "1/8 cft.", vol_met: ".0035 m3", benchmark: "Average party balloon" },
  "-2": { mass_imp: "6 lbs.", mass_met: "6 kg", time: "1 second", dist_imp: "1 foot", dist_met: "50 cm", vol_imp: "1/4 cft.", vol_met: ".007 m3", benchmark: "Brick / A basketball" },
  "-1": { mass_imp: "12 lbs.", mass_met: "12 kg", time: "3 seconds", dist_imp: "3 feet", dist_met: "1 m", vol_imp: "1/2 cft.", vol_met: ".014 m3", benchmark: "—" },
  "0": { mass_imp: "25 lbs.", mass_met: "24 kg", time: "6 seconds", dist_imp: "6 feet", dist_met: "2 m", vol_imp: "1 cubic ft. (cft.)", vol_met: ".025 m3", benchmark: "A person’s height / Crawling" },
  "1": { mass_imp: "50 lbs.", mass_met: "50 kg", time: "12 seconds", dist_imp: "15 feet", dist_met: "4 m", vol_imp: "3 cft.", vol_met: ".05 m3", benchmark: "Walking" },
  "2": { mass_imp: "100 lbs.", mass_met: "100 kg", time: "30 seconds", dist_imp: "30 feet", dist_met: "8 m", vol_imp: "6 cft.", vol_met: ".1 m3", benchmark: "Dashing / Average bathtub" },
  "3": { mass_imp: "200 lbs.", mass_met: "200 kg", time: "1 minute", dist_imp: "60 feet", dist_met: "16 m", vol_imp: "15 cft.", vol_met: ".2 m3", benchmark: "Adult human / Running / 55 gallon drum" },
  "4": { mass_imp: "400 lbs.", mass_met: "400 kg", time: "2 minutes", dist_imp: "120 feet", dist_met: "32 m", vol_imp: "30 cft.", vol_met: ".4 m3", benchmark: "Motorcycle / Average refrigerator" },
  "5": { mass_imp: "800 lbs.", mass_met: "800 kg", time: "4 minutes", dist_imp: "250 feet", dist_met: "64 m", vol_imp: "60 cft.", vol_met: ".8 m3", benchmark: "Adult grizzly bear" },
  "6": { mass_imp: "1,600 lbs.", mass_met: "1600 kg", time: "8 minutes", dist_imp: "500 feet", dist_met: "125 m", vol_imp: "120 cft.", vol_met: "1.7 m3", benchmark: "U.S. football field length" },
  "7": { mass_imp: "3,200 lbs.", mass_met: "3.2 tons", time: "15 minutes", dist_imp: "900 feet", dist_met: "250 m", vol_imp: "250 cft.", vol_met: "3.5 m3", benchmark: "30-ft. oak tree / Average highway speed" },
  "8": { mass_imp: "3 tons", mass_met: "6 tons", time: "30 minutes", dist_imp: "1,800 feet", dist_met: "500 m", vol_imp: "500 cft.", vol_met: "7 m3", benchmark: "Car / Empire State Building height" },
  "9": { mass_imp: "6 tons", mass_met: "12 tons", time: "1 hour", dist_imp: "1/2 mile", dist_met: "1 km", vol_imp: "1,000 cft.", vol_met: "15 m3", benchmark: "Ambulance / Average school bus" },
  "10": { mass_imp: "12 tons", mass_met: "25 tons", time: "2 hours", dist_imp: "1 mile", dist_met: "2 km", vol_imp: "2,000 cft.", vol_met: "30 m3", benchmark: "Small fire engine" },
  "11": { mass_imp: "25 tons", mass_met: "50 tons", time: "4 hours", dist_imp: "2 miles", dist_met: "4 km", vol_imp: "4,000 cft.", vol_met: "60 m3", benchmark: "Speed of sound / 40 ft. shipping container" },
  "12": { mass_imp: "50 tons", mass_met: "100 tons", time: "8 hours", dist_imp: "4 miles", dist_met: "8 km", vol_imp: "8,000 cft.", vol_met: "120 m3", benchmark: "Jet fighter / Average to the horizon" },
  "13": { mass_imp: "100 tons", mass_met: "200 tons", time: "16 hours", dist_imp: "8 miles", dist_met: "16 km", vol_imp: "16,000 cft.", vol_met: "250 m3", benchmark: "Main battle tank / Mach 4" },
  "14": { mass_imp: "200 tons", mass_met: "400 tons", time: "1 day", dist_imp: "16 miles", dist_met: "32 km", vol_imp: "30,000 cft.", vol_met: "500 m3", benchmark: "Two-story house / Length of Manhattan" },
  "15": { mass_imp: "400 tons", mass_met: "800 tons", time: "2 days", dist_imp: "30 miles", dist_met: "64 km", vol_imp: "60,000 cft.", vol_met: "1,000 m3", benchmark: "Statue of Liberty / Escape velocity on Earth" },
  "16": { mass_imp: "800 tons", mass_met: "1.6 ktons", time: "4 days", dist_imp: "60 miles", dist_met: "125 km", vol_imp: "120,000 cft.", vol_met: "2,000 m3", benchmark: "Loaded Boeing 747" },
  "17": { mass_imp: "1,600 tons", mass_met: "3.2 ktons", time: "1 week", dist_imp: "120 miles", dist_met: "250 km", vol_imp: "250,000 cft.", vol_met: "4,000 m3", benchmark: "Loaded passenger train" },
  "18": { mass_imp: "3,200 tons", mass_met: "6 ktons", time: "2 weeks", dist_imp: "250 miles", dist_met: "500 km", vol_imp: "500,000 cft.", vol_met: "8,000 m3", benchmark: "—" },
  "19": { mass_imp: "6,000 tons", mass_met: "12 ktons", time: "1 month", dist_imp: "500 miles", dist_met: "1,000 km", vol_imp: "1 million cft.", vol_met: "15,000 m3", benchmark: "Boston to Washington DC" },
  "20": { mass_imp: "12,000 tons", mass_met: "25 ktons", time: "2 months", dist_imp: "1,000 miles", dist_met: "2,000 km", vol_imp: "2 million cft.", vol_met: "30,000 m3", benchmark: "The Eiffel Tower" },
  "21": { mass_imp: "25,000 tons", mass_met: "50 ktons", time: "4 months", dist_imp: "2,000 miles", dist_met: "4,000 km", vol_imp: "4 million cft.", vol_met: "60,000 m3", benchmark: "—" },
  "22": { mass_imp: "50,000 tons", mass_met: "100 ktons", time: "8 months", dist_imp: "4,000 miles", dist_met: "8,000 km", vol_imp: "8 million cft.", vol_met: "125,000 m3", benchmark: "Battleship / Width of North America" },
  "23": { mass_imp: "100,000 tons", mass_met: "200 ktons", time: "1.5 years", dist_imp: "8,000 miles", dist_met: "16,000 km", vol_imp: "16 million cft.", vol_met: "500,000 m3", benchmark: "Aircraft carrier" },
  "24": { mass_imp: "200,000 tons", mass_met: "400 ktons", time: "3 years", dist_imp: "16,000 miles", dist_met: "32,000 km", vol_imp: "32 million cft.", vol_met: "1 million m3", benchmark: "—" },
  "25": { mass_imp: "400,000 tons", mass_met: "800 ktons", time: "6 years", dist_imp: "32,000 miles", dist_met: "64,000 km", vol_imp: "64 million cft.", vol_met: "2 million m3", benchmark: "Circumference of the Earth" },
  "26": { mass_imp: "800,000 tons", mass_met: "1,600 ktons", time: "12 years", dist_imp: "64,000 miles", dist_met: "124,000 km", vol_imp: "120 million cft.", vol_met: "4 million m3", benchmark: "—" },
  "27": { mass_imp: "1,600,000 tons", mass_met: "3,200 ktons", time: "25 years", dist_imp: "125,000 miles", dist_met: "250,000 km", vol_imp: "250 million cft.", vol_met: "8 million m3", benchmark: "The Golden Gate Bridge" },
  "28": { mass_imp: "3,200,000 tons", mass_met: "6,400 ktons", time: "50 years", dist_imp: "250,000 miles", dist_met: "500,000 km", vol_imp: "500 million cft.", vol_met: "16 million m3", benchmark: "Earth to the Moon" },
  "29": { mass_imp: "6,400,000 tons", mass_met: "12,500 ktons", time: "100 years", dist_imp: "500,000 miles", dist_met: "1 million km", vol_imp: "1 billion cft.", vol_met: "32 million m3", benchmark: "The Great Pyramid of Giza" },
  "30": { mass_imp: "12,500,000 tons", mass_met: "25,000 ktons", time: "200 years", dist_imp: "1 million miles", dist_met: "2 million km", vol_imp: "2 billion cft.", vol_met: "64 million m3", benchmark: "The speed of light" }
};

const SIZE_TABLE = {
  "Awesome": { rank: 5, spaces: "8", reach: "6", defense: -5, damage: 5, toughness: 5, speed: 5, intimidation: 10, stealth: -10 },
  "Colossal": { rank: 4, spaces: "6", reach: "4", defense: -4, damage: 4, toughness: 4, speed: 4, intimidation: 8, stealth: -8 },
  "Gargantuan": { rank: 3, spaces: "4", reach: "3", defense: -3, damage: 3, toughness: 3, speed: 3, intimidation: 6, stealth: -6 },
  "Huge": { rank: 2, spaces: "3", reach: "2", defense: -2, damage: 2, toughness: 2, speed: 2, intimidation: 4, stealth: -4 },
  "Large": { rank: 1, spaces: "2", reach: "1", defense: -1, damage: 1, toughness: 1, speed: 1, intimidation: 2, stealth: -2 },
  "Medium": { rank: 0, spaces: "1", reach: "1", defense: 0, damage: 0, toughness: 0, speed: 0, intimidation: 0, stealth: 0 },
  "Small": { rank: -1, spaces: "1", reach: "1", defense: 1, damage: -1, toughness: -1, speed: -1, intimidation: -2, stealth: 2 },
  "Tiny": { rank: -2, spaces: "1/2", reach: "0", defense: 2, damage: -2, toughness: -2, speed: -2, intimidation: -4, stealth: 4 },
  "Diminutive": { rank: -3, spaces: "1/4", reach: "0", defense: 3, damage: -3, toughness: -3, speed: -3, intimidation: -6, stealth: 6 },
  "Fine": { rank: -4, spaces: "1/8", reach: "0", defense: 4, damage: -4, toughness: -4, speed: -4, intimidation: -8, stealth: 8 },
  "Minuscule": { rank: -5, spaces: "1/16", reach: "0", defense: 5, damage: -5, toughness: -5, speed: -5, intimidation: -10, stealth: 10 }
};

const PL_LIMITS = {
  "1": { maxSkill: 11, maxAttackEffect: 2, maxDefTough: 2, maxFortWill: 2, maxHeroicAdv: 0 },
  "2": { maxSkill: 12, maxAttackEffect: 4, maxDefTough: 4, maxFortWill: 4, maxHeroicAdv: 1 },
  "3": { maxSkill: 13, maxAttackEffect: 6, maxDefTough: 6, maxFortWill: 6, maxHeroicAdv: 1 },
  "4": { maxSkill: 14, maxAttackEffect: 8, maxDefTough: 8, maxFortWill: 8, maxHeroicAdv: 2 },
  "5": { maxSkill: 15, maxAttackEffect: 10, maxDefTough: 10, maxFortWill: 10, maxHeroicAdv: 2 },
  "6": { maxSkill: 16, maxAttackEffect: 12, maxDefTough: 12, maxFortWill: 12, maxHeroicAdv: 3 },
  "7": { maxSkill: 17, maxAttackEffect: 14, maxDefTough: 14, maxFortWill: 14, maxHeroicAdv: 3 },
  "8": { maxSkill: 18, maxAttackEffect: 16, maxDefTough: 16, maxFortWill: 16, maxHeroicAdv: 4 },
  "9": { maxSkill: 19, maxAttackEffect: 18, maxDefTough: 18, maxFortWill: 18, maxHeroicAdv: 4 },
  "10": { maxSkill: 20, maxAttackEffect: 20, maxDefTough: 20, maxFortWill: 20, maxHeroicAdv: 5 },
  "11": { maxSkill: 21, maxAttackEffect: 22, maxDefTough: 22, maxFortWill: 22, maxHeroicAdv: 5 },
  "12": { maxSkill: 22, maxAttackEffect: 24, maxDefTough: 24, maxFortWill: 24, maxHeroicAdv: 6 },
  "13": { maxSkill: 23, maxAttackEffect: 26, maxDefTough: 26, maxFortWill: 26, maxHeroicAdv: 6 },
  "14": { maxSkill: 24, maxAttackEffect: 28, maxDefTough: 28, maxFortWill: 28, maxHeroicAdv: 7 },
  "15": { maxSkill: 25, maxAttackEffect: 30, maxDefTough: 30, maxFortWill: 30, maxHeroicAdv: 7 },
  "16": { maxSkill: 26, maxAttackEffect: 32, maxDefTough: 32, maxFortWill: 32, maxHeroicAdv: 8 },
  "17": { maxSkill: 27, maxAttackEffect: 34, maxDefTough: 34, maxFortWill: 34, maxHeroicAdv: 8 },
  "18": { maxSkill: 28, maxAttackEffect: 36, maxDefTough: 36, maxFortWill: 36, maxHeroicAdv: 9 },
  "19": { maxSkill: 29, maxAttackEffect: 38, maxDefTough: 38, maxFortWill: 38, maxHeroicAdv: 9 },
  "20": { maxSkill: 30, maxAttackEffect: 40, maxDefTough: 40, maxFortWill: 40, maxHeroicAdv: 10 }
};

const ACTIONS_TABLE = [
  { name: "Aid", type: "Standard", check: "DC 10 Attack", effect: "1DoS: +2 attack or Defense Bonus, 3+DoS: +5 bonus." },
  { name: "Aim", type: "Standard", check: "None", effect: "Roll two dice of next attack, use the better of the two." },
  { name: "Attack", type: "Standard", check: "Attack vs. Defense", effect: "1+DoS: Hit, Added Success: Critical Hit, +5 effect" },
  { name: "Block", type: "Standard", check: "Attack vs. Attack", effect: "1+DoS: Attack blocked" },
  { name: "Catch", type: "Reaction", check: "DC 10 Agility", effect: "Catch a free-falling object within Reach" },
  { name: "Charge", type: "Standard", check: "Attack –2 vs. Defense", effect: "Move your speed, then make a close attack" },
  { name: "Command", type: "Simple", check: "None", effect: "Issue a command to a character under your direction" },
  { name: "Concentrate", type: "Standard", check: "None", effect: "Concentrate to maintain an effect" },
  { name: "Defend", type: "Standard", check: "None", effect: "+2 bonus to Defense until the start of your next turn." },
  { name: "Disarm", type: "Standard", check: "Attack –2 vs. Defense", effect: "Damage vs. Strength check, 1+DoS disarms defender." },
  { name: "Drop Prone", type: "Free", check: "None", effect: "Character gains the Prone condition." },
  { name: "Escape", type: "Simple", check: "Str or Sleight of Hand", effect: "Strength or Slight of Hand vs. grab effect DC. 1 DoS ends the grab, 2+DoS move your speed –1 as well." },
  { name: "Feint", type: "Standard", check: "Attack", effect: "Check vs. Attack, Deception, or Insight. 1DoS: Target is Vulnerable against your next attack." },
  { name: "Grab", type: "Standard", check: "Attack vs. Defense", effect: "Str vs. Str or Dodge check. 1DoS: partial hold, 2+DoS: complete hold." },
  { name: "Impress", type: "Standard", check: "Interaction skill", effect: "vs. same skill, Insight, or Will. Success imposes conditions." },
  { name: "Move", type: "Simple", check: "None", effect: "Move your normal speed, DC 15 Athletics for +1 speed." },
  { name: "Observe", type: "Simple", check: "Perception", effect: "Try to perceive something new." },
  { name: "Ready", type: "Standard", check: "None", effect: "Ready another action to perform later when triggered." },
  { name: "Recover", type: "Standard", check: "DC 10 Stamina", effect: "Recover from a damage condition, +2 Defense" },
  { name: "Smash", type: "Standard", check: "Attack -2 vs. Defense", effect: "Inflict damage on the held object with success." },
  { name: "Stand", type: "Free", check: "DC 20 Acrobatics", effect: "or becoming Hindered until next turn to end prone condition" },
  { name: "Sustain", type: "Free", check: "None", effect: "Maintain an effect." },
  { name: "Trick", type: "Standard", check: "Deception", effect: "vs. Deception or Insight. Success leaves opponent heedless of danger or risk." },
  { name: "Trip", type: "Standard", check: "Attack vs. Defense", effect: "Str vs. Str or Dodge, 1DoS: target prone." },
  { name: "Use Effect", type: "Varies", check: "Varies (if any)", effect: "By effect. See descriptions in the Powers chapter." }
];